### ISSUE TITLE
账号无法登录，content一直显示错误，不管我怎么输入

### ISSUE THREAD

**Issue by frozenblackflame** [enpitsuLin/rhodes-headquarters#18]
账号无法登录，content一直显示错误，不管我怎么输入

**Comment by enpitsuLin** [comment]
如果是扩展商店的话确实用不了 😇 等 #16 合入再去提审一下，如果有兴趣的话可以自己运行开发还是可以用的

**Comment by suDexter** [comment]
试了一下，还是一直报错验证出错

**Comment by frozenblackflame** [comment]
> 试了一下，还是一直报错验证
他的意思是直接clone项目，本地运行，会有自动在目录生成插件文件夹，然后卸载谷歌商店下载的，安装自动生成的那个插件。每次运行前先运行项目。

**Comment by frozenblackflame** [comment]
> 试了一下，还是一直报错验证出错

他的意思是，clone项目本地运行，会在目录下生成一个插件文件夹。安装这个自动生成的就行。别忘了吧谷歌商店下载的删掉。
**~\rhodes-headquarters\.output\chrome-mv3**这个文件夹就是插件文件夹

**Comment by enpitsuLin** [comment]
新版本 v0.3.0 已经发布到 [Google 扩展商店](https://chromewebstore.google.com/detail/cbnldploflpmmkmcbhipaoojkdmillkm) 可以直接通过这里安装了
