### ISSUE TITLE
商店的版本需要更新

### ISSUE THREAD

**Issue by whitecodes** [enpitsuLin/rhodes-headquarters#3]
从商店下载的版本现在不能登录

**Comment by enpitsuLin** [comment]
唔 居然有人在用吗 那我去发布一版新的临时代替一下吧 现在正在重构的路上

**Comment by enpitsuLin** [comment]
<img width="585" alt="image" src="https://github.com/enpitsuLin/rhodes-headquarters/assets/29378026/9b9178aa-2de3-4a74-8d18-0d47b49e48f1"> 提交审核中，先保证 YJ 新的 signature 头验证能用了，后面界面优化和咕咕咕的基建功能应该也会慢慢加上

**Comment by enpitsuLin** [comment]
已发布 0.1.0-beta.0
